language: java
jdk:
- oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
install: true
script: mvn clean install
after_success:
- mvn clean test jacoco:report coveralls:report
